### ISSUE TITLE
Plaid 9.0.0-beta.13 itemRemove throwing error on every call

### ISSUE THREAD

**Issue by andrewheekin** [plaid/plaid-node#450] opened 2021-06-23 12:17 UTC
Calling itemRemove fails for me every time. Using valid accessTokens, secret, client_id

Unexpected behavior:  throws an error with a message of undefined and response of an empty JS object

```
const plaid = require('plaid')
const { Configuration, PlaidApi, PlaidEnvironments } = plaid;

const configuration = new Configuration({
  basePath: PlaidEnvironments.production,
  baseOptions: {
    headers: {
      'PLAID-CLIENT-ID': process.env.PLAID_CLIENT_ID,
      'PLAID-SECRET': process.env.PLAID_SECRET,
      'Plaid-Version': '2020-09-14',
    },
  },
});

const client = new PlaidApi(configuration);

let plaidItemRemoveResponse;
let accessToken = "an active accessToken";
try {
     plaidItemRemoveResponse = await client.itemRemove({ access_token: accessToken, client_id: process.env.PLAID_CLIENT_ID, secret: process.env.PLAID_SECRET});
    console.log(`Successfully removed Plaid Item: ${JSON.stringify(plaidItemRemoveResponse)}\n`)
} catch (err) {
    console.log(`Error in Plaid Item removal: ${JSON.stringify(err)}\n`);
}
```

**Comment by phoenixy1** [comment] 2021-06-28 22:50
@andrewheekin can you take a look at the dashboard logs and see if you can pull a `request_id` for one of these requests and share it with us? It's not obvious from the openapi file what's going wrong here so I'm hoping that looking at the details of the request from our end might help explain it. my intuition is that possibly the version is not getting set correctly because I know this is an endpoint whose schema changed in the latest API version, but your code to set the version seems to be correct...

**Comment by phoenixy1** [comment] 2021-08-10 19:40
So we have been unable to reproduce this internally and do not have debugging information from reporter, so are closing -- feel free to re-file if you can provide a `request_id`!

**Closed by phoenixy1** 2021-08-10 19:40 UTC
