### ISSUE TITLE
plaid@beta - "Cannot find module 'plaid' or its corresponding type declarations." after install

### ISSUE THREAD

**Issue by blakekrammes** [plaid/plaid-node#421] opened 2021-03-17 17:33 UTC
After running `yarn add plaid@beta` all my imports from `plaid` say the module cannot be found. I've tried deleting node_modules and reinstalling to no avail. 

<img width="501" alt="Screen Shot 2021-03-17 at 12 34 04 PM" src="https://user-images.githubusercontent.com/49688912/111511920-305af200-871d-11eb-8765-1cea33a55cff.png">

<img width="594" alt="Screen Shot 2021-03-17 at 12 34 49 PM" src="https://user-images.githubusercontent.com/49688912/111511926-318c1f00-871d-11eb-9c7a-4838c9743a18.png">

**Comment by gp187** [comment] 2021-03-21 21:47
+1 same issue!

**Comment by jbambery** [comment] 2021-03-22 00:21
+1 Me as well :(

**Comment by thdxr** [comment] 2021-03-25 15:31
The issue is the package is not built before publishing. `dist` contains typescript files and not js files

**Comment by cgfarmer4** [comment] 2021-03-29 22:06
Sorry for the bad publish on `beta 12` all. I will push a fix this week.

**Comment by cgfarmer4** [comment] 2021-03-31 06:17
This is resolved in `beta 13`. Thanks for the report @blakekrammes

**Closed by cgfarmer4** 2021-03-31 06:18 UTC
