### ISSUE TITLE
payment_initiation is not working

### ISSUE THREAD

**Issue by princerafid01** [plaid/plaid-node#311] opened 2020-06-20 14:38 UTC
Payment initiation is not working at all in this demo app. It says `the following required fields are missing: payment_token required for payment_initiation product` . And also it come to the console `client is not authorized to access the following products: [\"payment_initiation\"]`

**Comment by skylarmb** [comment] 2020-06-22 22:11
hi there @princerafid01 which demo app are you referring to? Your `client_id` must be enabled to access the `payment_initiation` product. This is not a bug with `plaid-node`.

You can request access to new products here: https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/request-product-access

**Comment by princerafid01** [comment] 2020-06-23 12:45
can i access this in sandbox mode ?

**Comment by skylarmb** [comment] 2020-06-25 04:36
@princerafid01 `payment_initiation` is a product that is not enabled by default in sandbox, you can reach out to the support team at the link above to request access to this product in sandbox. Thanks! I am going to close this issue for now as its not an issue with plaid-node

**Closed by skylarmb** 2020-06-25 04:36 UTC
